version: '2.2'
services: 
  ############################################ app ############################################
  app:
    container_name: 'ButlingButler-app'
    restart: unless-stopped
    build: .
    environment:
      - ON_HEROKU=1
      - ASKJEEVES_USERNAME=askjeeves
      - ASKJEEVES_PASSWORD=askjeeves
      - DATABASE_URL=postgres://butlingbutler:changeme@postgres:5432/butlingbutler
      - PORT=5000
    networks: 
      - default
      - backend
    ports: 
      - 5000:5000
    depends_on:
      - postgres
    cpus: 1
    mem_limit: 150M

  ############################################ MySQL ############################################
  postgres:
    container_name: ButlingButler-postgres
    restart: unless-stopped
    image: postgres:9.6 
    environment: 
      POSTGRES_DB: "butlingbutler"
      POSTGRES_USER: "butlingbutler"
      POSTGRES_PASSWORD: "changeme"
    networks:
      - backend
    volumes: 
      - postgres-db:/var/lib/postgresql/data
    cpus: 1
    mem_limit: 150M

networks: 
  backend:
  
volumes: 
  postgres-db: