version: '2.2'
services:
  ############################################ app ############################################
  app:
    container_name: askjeevessecbot-app
    restart: unless-stopped
    build: 
      context: AskJeeves
      dockerfile: Dockerfile-app
    networks:
      - kafka-backend
    depends_on:
      - kafka
      - mysql
      - rsyslog
    cpus: 2
    mem_limit: 150M

  
  ############################################ Rsyslog server ############################################
  rsyslog:
    container_name: askjeevessecbot-rsyslog
    restart: unless-stopped
    build:
      context: Rsyslog
      dockerfile: Dockerfile-rsyslog
    ports:
      - 1514:1514/udp
    networks: 
      - default
      - logging-backend
      - kafka-backend
    depends_on:
      - kafka
    cpus: 2
    mem_limit: 150M

  ############################################ MySQL ############################################
  mysql:
    container_name: askjeevessecbot-mysql
    restart: unless-stopped
    image: mysql:5.7
    #image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_DATABASE: "askjeevessecbot"
      MYSQL_USER: "askjeevessecbot"
      MYSQL_PASSWORD: "changeme"
      MYSQL_ROOT_HOST: '%'
    networks:
      - kafka-backend
    volumes: 
      - mysql-db:/var/lib/mysql
    depends_on:
      - kafka
    cpus: 1
    mem_limit: 150M

    
  ############################################ Zookeeper ############################################
  zookeeper:
    container_name: askjeevessecbot-zookeeper
    restart: unless-stopped
    image: "confluentinc/cp-zookeeper:5.4.1"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks: 
      - kafka-backend
    cpus: 1
    mem_limit: 150M
  
  ############################################ Kafka server ############################################
  kafka:
    container_name: askjeevessecbot-kafka
    restart: unless-stopped
    image: "confluentinc/cp-enterprise-kafka:5.4.1"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:39092,EXTERNAL_NETWORK://kafka.hackinglab.local:29092
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL_NETWORK:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:39092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:32181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    networks:
      - logging-backend
      - kafka-backend
    depends_on:
      - zookeeper
    cpus: 2
    mem_limit: 1G

volumes:
  mysql-db:

networks: 
  kafka-backend:
  logging-backend: