Slack:
  token: "xoxb-211945973922-1006366090577-wE3kPdn2LP9O9MejygaiCrsp"
kafka:
  hostname: "kafka.hackinglab.local"
  port: 29092
  groupId: 1
  offset: "latest"
  consumer_topic: "vpn-log-raw"
  poll_interval: 3
mysql:
  hostname: "kafka.hackinglab.local"
  port: 3306
  protocol: "tcp"
  database: "askjeevessecbot"
  username: "askjeevessecbot"
  password: "changeme"
  expire: 30
GeoIP:
  file_path: "data/GeoLite2-City.mmdb"
  api_key: ""