Slack:
  token: "slack_token_here"
kafka:
  hostname: "docker_ip_addr"
  port: 29092
  groupId: 1
  offset: "latest"
  consumer_topic: "vpn-log-raw"
  poll_interval: 3
mysql:
  hostname: "docker_ip_addr"
  port: 3306
  protocol: "tcp"
  database: "askjeevessecbot"
  username: "askjeevessecbot"
  password: "mysql_password_here"
  expire: 90 # 90 days
  interval: 21600 # 6 hours
GeoIP:
  file_path: "data/GeoLite2-City.mmdb"
  url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=%s&suffix=tar.gz"
  license_key: "max_mind_license_key_here"
ButlingButler:
  url: "http://butling_butler_url"
  username: "butling_butler_user_here"
  password: "butling_butler_password_here"
  interval: 300 # 5 minutes
theHive:
  url: "https://thehive.local"
  api_key: "the_hive_key_here"
