FROM golang:1.13
WORKDIR /go/src/app
COPY app /go/src/app

RUN go get -d -v ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM ubuntu:18.04
RUN apt-get update -y && apt-get install -y librdkafka-dev
WORKDIR /root/
COPY --from=0 /go/src/app .
CMD ["./app"]  