FROM golang:1.13-alpine as build

# Set working dir and copy app
WORKDIR /go/src/app
COPY /app /go/src/app/
 
# Downlaod GOLANG packages
RUN go mod download

# Compile app
RUN CGO_ENABLED=0 GOOS=linux go build -o butlingbutler .

FROM alpine:latest

# Create user
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Make app directory
RUN mkdir -p /app{config,data}
WORKDIR /app

# Copy binary from abive
COPY --from=build /go/src/app/butlingbutler /app/butlingbutler

# Copy config and GeoIP database
COPY app/config/config.yaml /app/config/config.yaml

# Set perms to user
RUN chown appuser:appuser -R /app

USER appuser

CMD ["/app/butlingbutler"]  