FROM ubuntu:18.04

#### Install/Setup Ryslog ####
RUN apt-get update -y
RUN apt-get install rsyslog rsyslog-kafka -y

#### Copy configs ####
RUN rm /etc/rsyslog.d/50-default.conf 

# Main rsyslog config
COPY conf/rsyslog-server/rsyslog.conf /etc/rsyslog.conf

# Input config
COPY conf/rsyslog-server/10-input-udp.conf /etc/rsyslog.d/10-input-udp.conf

# Kafka configs
COPY conf/rsyslog-server/30-output-kafka.conf /etc/rsyslog.d/30-output-kafka.conf

# Expose port
EXPOSE 1514/udp

# Run rsyslog
CMD ["/usr/sbin/rsyslogd", "-n", "-f", "/etc/rsyslog.conf"]